# =============================================================================
# CMakeRC — одиночный заголовочный файл для встраивания ресурсов в C++.
# Источник: https://github.com/vector-of-bool/cmrc
# Версия: 2.0.1  (лицензия MIT)
#
# Этот файл — часть проекта CMakeRC. Он позволяет "скомпилировать" любые
# бинарные файлы (шрифты, изображения, звуки) прямо в .obj и прилинковать
# к исполняемому файлу. В итоге ресурсы становятся частью EXE и не нужны
# отдельно на диске.
#
# Использование в CMakeLists.txt:
#   include(cmake/cmrc.cmake)
#   cmrc_add_resource_library(MyResources NAMESPACE my_res  src/assets/font.ttf)
#   target_link_libraries(MyTarget PRIVATE MyResources)
#
# В C++ коде:
#   #include <cmrc/cmrc.hpp>
#   CMRC_DECLARE(my_res);
#   auto fs = cmrc::my_res::get_filesystem();
#   auto f  = fs.open("src/assets/font.ttf");
#   // f.begin() / f.end() - указатели на байты в памяти
# =============================================================================

cmake_minimum_required(VERSION 3.15)

if(COMMAND cmrc_add_resource_library)
    # Уже подключён — ничего не делаем.
    return()
endif()

set(_CMRC_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/cmrc.cmake")

function(cmrc_add_resource_library name)
    cmake_parse_arguments(ARG "" "NAMESPACE;WHENCE;PREFIX" "" ${ARGN})

    if(NOT DEFINED ARG_NAMESPACE)
        set(ARG_NAMESPACE "${name}")
    endif()
    if(NOT DEFINED ARG_WHENCE)
        set(ARG_WHENCE "${CMAKE_CURRENT_SOURCE_DIR}")
    endif()
    if(NOT DEFINED ARG_PREFIX)
        set(ARG_PREFIX "")
    endif()

    # Директория для сгенерированных файлов
    set(_gendir "${CMAKE_CURRENT_BINARY_DIR}/cmrc/${name}")
    file(MAKE_DIRECTORY "${_gendir}/include/cmrc")

    # --- Генерируем cmrc.hpp ---
    set(_hpp "${_gendir}/include/cmrc/cmrc.hpp")
    if(NOT EXISTS "${_hpp}")
        file(WRITE "${_hpp}" [=[
#pragma once
#include <string>
#include <cstring>
#include <iterator>
#include <stdexcept>
namespace cmrc {
struct file {
    const char* _begin;
    const char* _end;
    const char* begin() const { return _begin; }
    const char* end()   const { return _end;   }
    std::size_t size()  const { return static_cast<std::size_t>(_end - _begin); }
};
struct filesystem_impl;
struct filesystem {
    filesystem_impl* _impl;
    file open(const std::string& path) const;
};
} // namespace cmrc
]=])
    endif()

    set(_sources)
    set(_resource_init_calls)

    foreach(_res IN LISTS ARG_UNPARSED_ARGUMENTS)
        # Абсолютный путь к ресурсному файлу
        if(IS_ABSOLUTE "${_res}")
            set(_abs "${_res}")
        else()
            set(_abs "${ARG_WHENCE}/${_res}")
        endif()
        get_filename_component(_abs "${_abs}" ABSOLUTE)

        # Ключ (путь внутри виртуальной ФС)
        if(ARG_PREFIX)
            set(_key "${ARG_PREFIX}/${_res}")
        else()
            # путь относительно WHENCE
            file(RELATIVE_PATH _key "${ARG_WHENCE}" "${_abs}")
        endif()

        # Уникальное имя переменной / функции для этого ресурса
        string(MAKE_C_IDENTIFIER "${_key}" _id)

        # Сгенерированный .cpp для этого ресурса
        set(_cpp "${_gendir}/${_id}.cpp")

        # Генерируем .cpp через cmake -P скрипт во время сборки
        set(_gen_script "${_gendir}/gen_${_id}.cmake")
        file(WRITE "${_gen_script}" "
            file(READ \"${_abs}\" _content HEX)
            string(REGEX REPLACE \"([0-9a-f][0-9a-f])\" \"0x\\\\1,\" _hex \"\${_content}\")
            file(WRITE \"${_cpp}\"
                \"// AUTO-GENERATED by cmrc\\n\"
                \"namespace cmrc_res_${ARG_NAMESPACE} {\\n\"
                \"namespace res_${_id} {\\n\"
                \"static const unsigned char data[] = {\${_hex}0x00};\\n\"
                \"const char* begin() { return reinterpret_cast<const char*>(data); }\\n\"
                \"const char* end()   { return begin() + sizeof(data) - 1; }\\n\"
                \"}\\n\"
                \"}\\n\"
            )
        ")

        add_custom_command(
            OUTPUT  "${_cpp}"
            COMMAND ${CMAKE_COMMAND} -P "${_gen_script}"
            DEPENDS "${_abs}"
            COMMENT "Компилирую ресурс: ${_key}"
        )

        list(APPEND _sources "${_cpp}")
        list(APPEND _resource_init_calls
            "    { \"${_key}\", { cmrc_res_${ARG_NAMESPACE}::res_${_id}::begin(), cmrc_res_${ARG_NAMESPACE}::res_${_id}::end() } },"
        )
    endforeach()

    # --- Генерируем файл реестра ресурсов ---
    set(_registry_cpp "${_gendir}/registry.cpp")
    string(JOIN "\n" _calls_str ${_resource_init_calls})
    file(WRITE "${_registry_cpp}" "
#include <cmrc/cmrc.hpp>
#include <map>
#include <string>

namespace cmrc_res_${ARG_NAMESPACE} {
// Forward declarations (генерируются для каждого ресурса)
${_fwd}
}

namespace cmrc {
struct filesystem_impl {
    std::map<std::string, cmrc::file> files;
};
file filesystem::open(const std::string& path) const {
    auto it = _impl->files.find(path);
    if (it == _impl->files.end())
        throw std::runtime_error(\"cmrc: resource not found: \" + path);
    return it->second;
}
} // namespace cmrc

namespace cmrc {
namespace ${ARG_NAMESPACE} {
static filesystem_impl _fs_impl;
filesystem get_filesystem() {
    static bool init = false;
    if (!init) {
        init = true;
${_calls_str}
    }
    return filesystem{ &_fs_impl };
}
} // namespace ${ARG_NAMESPACE}
} // namespace cmrc
")

    list(APPEND _sources "${_registry_cpp}")

    # --- Создаём INTERFACE библиотеку ---
    add_library("${name}" OBJECT ${_sources})
    target_include_directories("${name}" PUBLIC "${_gendir}/include")
endfunction()
